server:
    port: 9090
spring:
    datasource:
        password: admin2021
        url: jdbc:postgresql://localhost:5432/ai
        username: dbuser
    #    sql:
    #        init:
    #            mode: always
    jpa:
        hibernate:
            ddl-auto: update
        #            ddl-auto: create
        #            initialization-mode: always
        #            defer-datasource-initialization: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
                show_sql: true
                format_sql: true
    flyway:
        # 是否启用flyway
        enabled: false
        # 编码格式，默认UTF-8
        encoding: UTF-8
        # 迁移sql脚本文件存放路径，默认db/migration
        locations: classpath:db/migration
        # 迁移sql脚本文件名称的前缀，默认V
        sql-migration-prefix: V
        # 迁移sql脚本文件名称的分隔符，默认2个下划线__
        sql-migration-separator: __
        # 迁移sql脚本文件名称的后缀
        sql-migration-suffixes: .sql
        # 迁移时是否进行校验，默认true
        validate-on-migrate: true
        # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
        baseline-on-migrate: true
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            auto-offset-reset: earliest
#            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            #value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

login:
    token-key: Authorization

jwt:
    # jwt密钥，验签需要
    secret: rstyro2dcad64e9cbd542c5584f1103110e6ce2dcad64e9cbd542c5584rstyro
    # 过期时间单位：分钟
    expireTime: 6000
    subject: token

logging:
    level:
        com:
            ai:
                sys: DEBUG
        org:
            springframework: DEBUG
            #          security: DEBUG
            hibernate:
                type: trace

algoconsumer:
    dockerhost: tcp://localhost:2375

workspace:
#    algo: /Users/liujun/Desktop/AI/algos
#    dataset: /Users/liujun/Desktop/AI/datasets
#    upload: /Users/liujun/Desktop/AI/uploads
#    result: /Users/liujun/Desktop/AI/results
#    model: /Users/liujun/Desktop/AI/models
#    resultsuffix: .res
#    sourcesuffix: .zip
    algo: D:\code\ai\src\test\algos
    dataset: D:\code\ai\src\test\datasets
    upload: D:\code\ai\src\test\uploads
    result: D:\code\ai\src\test\results
    model: D:\code\ai\src\test\models
    resultsuffix: .res
    sourcesuffix: .zip

